agents/urls.py
from django.urls import path

from .views import (
    AgentCreateView,
    AgentDeleteView,
    AgentDetailView,
    AgentListView,
    AgentUpdateView,
)

app_name = "agents"

urlpatterns = [
    path("", AgentListView.as_view(), name="agent-list"),
    path("create/", AgentCreateView.as_view(), name="agent-create"),
    path("agent/update/<int:pk>/", AgentUpdateView.as_view(), name="agent-update"),
    path("agent/delete/<int:pk>/", AgentDeleteView.as_view(), name="agent-delete"),
    path("agent/detail/<int:pk>/", AgentDetailView.as_view(), name="agent-detail"),
]

crm/urls.py
from django.urls import path

from . import views

app_name = "crm"

urlpatterns = [
    path("", views.LeadListView.as_view(), name="home"),
    path("create/", views.LeadCreateView.as_view(), name="lead-create"),
    path("update/<int:pk>/", views.LeadUpdateView.as_view(), name="lead-update"),
    path("delete/<int:pk>/", views.LeadDeleteView.as_view(), name="lead-delete"),
    path("detail/<int:pk>/", views.LeadDetailView.as_view(), name="lead-detail"),
    path(
        "assign-agent/<int:pk>/", views.AssignAgentView.as_view(), name="agent-assign"
    ),
    path("categories/", views.CategoryListView.as_view(), name="category-list"),
    path(
        "categories/<int:pk>/",
        views.CategoryDetailView.as_view(),
        name="category-detail",
    ),
    path(
        "categories/<int:pk>/update/",
        views.LeadCategoryUpdateView.as_view(),
        name="lead-category-update",
    ),
    path(
        "create/category/", views.CategoryCreateView.as_view(), name="category-create"
    ),
    path(
        "update/<int:pk>/category/",
        views.CategoryUpdateView.as_view(),
        name="category-update",
    ),
    path(
        "delete/<int:pk>/category",
        views.CategoryDeleteView.as_view(),
        name="category-delete",
    ),
]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import include, path

from crm.views import LandingPageView, SignupView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", LandingPageView.as_view(), name="landing-page"),
    path("leads/", include("crm.urls", namespace="crm")),
    path("agents/", include("agents.urls", namespace="agents")),
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("reset_password/", PasswordResetView.as_view(), name="reset_password"),
    path(
        "password_reset_done/",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name")

agents/views.py
# from django.contrib.auth.mixins import LoginRequiredMixin
import random

from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.urls import reverse
from django.views import generic

from crm.models import Agent

from .forms import AgentModelForm
from .mixins import OrganizerAndLoginRequiredMixin

# Create your views here.
User = get_user_model()


class AgentListView(OrganizerAndLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)


class AgentCreateView(OrganizerAndLoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent-list")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organizer = False
        user.set_password(f"{random.randint(0, 1000000)}")
        user.save()
        Agent.objects.create(user=user, organization=self.request.user.userprofile)
        send_mail(
            subject="You are invited to be an agent",
            message="You were added as an agent on DJCRM. Please come login and start working",
            from_email="test@user.com",
            recipient_list=[user.email],
        )
        # agent.organization = self.request.user.userprofile
        # agent.save()
        return super(AgentCreateView, self).form_valid(form)


class AgentDetailView(OrganizerAndLoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_detail.html"
    context_object_name = "agent"

    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)


class AgentUpdateView(OrganizerAndLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    context_object_name = "agent"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent-list")

    def get_queryset(self):
        organization = self.request.user.userprofile
        qs = Agent.objects.filter(organization=organization)
        return qs

    # since we are using a different model in form we need to send the user attribute of the agent model as the instance to update the user details
    def get_form_kwargs(self, **kwargs):
        kwargs = super().get_form_kwargs(**kwargs)
        kwargs["instance"] = kwargs["instance"].user
        return kwargs


class AgentDeleteView(OrganizerAndLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_delete.html"
    context_object_name = "agent"

    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)

    def get_success_url(self):
        return reverse("agents:agent-list")

templates/agents/agent_create.html
{% extends "crm/base.html" %}
{% load tailwind_filters %}
{% block content %}
  <div class="max-w-lg mx-auto">
    <h1 class="mb-5 text-4xl text-gray-800">Create a new Agent</h1>
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button class="py-2 px-3 mb-1 border rounded-lg text-white bg-blue-500 hover:bg-blue-700"
              type="submit">Create</button>
      <a href="{% url 'agents:agent-list' %}"
         class="py-2 px-3 mb-1 border rounded-lg text-white bg-teal-600 hover:bg-green-800">Cancel</a>
    </form>
  </div>
{% endblock content %}

templates/agents/agent_delete.html
{% extends "crm/base.html" %}
{% load tailwind_filters %}
{% block content %}
  <div class="max-w-lg mx-auto">
    <h1 class="text-4xl mb-5">Are you sure you want to delete this Agent?</h1>
    <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit"
              class="py-2 px-3 mb-1 border-1 rounded-lg text-white bg-red-500 hover:bg-red-600">Submit</button>
      <a href="{% url 'agents:agent-detail' pk=agent.pk %}"
         class="py-2 px-3 mb-1 border-1 rounded-lg text-white bg-blue-500 hover:bg-blue-700">Cancel</a>
    </form>
  </div>
{% endblock content %}

templates/agents/agent_detail.html
{% extends "crm/base.html" %}
{% block title %}
  Agent - Detail
{% endblock title %}
{% block content %}
  <section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
          <div class="flex mb-4">
            <a href="{% url 'agents:agent-detail' agent.pk %}"
               class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
              Overview
            </a>
            <a href="{% url 'agents:agent-update' agent.pk %}"
               class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Update Details
            </a>
          </div>
          <div class="flex border-t border-gray-300 py-2">
            <span class="text-gray-500">Full Name</span>
            <span class="ml-auto text-gray-900">{{ agent.user.first_name }} {{ agent.user.last_name }}</span>
          </div>
          <div class="flex border-t border-gray-300 py-2">
            <span class="text-gray-500">Email</span>
            <span class="ml-auto text-gray-900">{{ agent.user.email }}</span>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/agents/agent_list.html
{% extends "crm/base.html" %}
{% block title %}
  CRM - Agents
{% endblock title %}
{% block content %}
  <section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
      <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
          <h1 class="text-4xl text-gray-800">Agents</h1>
        </div>
        <div>
          <a class="text-gray-500 hover:text-blue-500"
             href="{% url 'agents:agent-create' %}">Create a new agent</a>
        </div>
      </div>
      <div class="flex flex-col w-full">
        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-100">
                  <tr>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Full Name</th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Email</th>
                    <th scope="col" class="relative px-6 py-3">
                      <span class="sr-only">Edit</span>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {% for agent in object_list %}
                    <tr class="bg-white">
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        {{ agent.user.first_name }} {{ agent.user.last_name }}
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ agent.user.email }}</td>
                      <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <a href="{% url 'agents:agent-update' agent.pk %}"
                           class="text-indigo-600 hover:text-indigo-900">Edit</a>
                      </td>
                    </tr>
                  {% empty %}
                    <p>There are currently no agents</p>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/agents/agent_update.html
{% extends "crm/base.html" %}
{% block title %}
  Agent - Update
{% endblock title %}
{% block content %}
  <section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
          <div class="flex mb-4">
            <a href="{% url 'agents:agent-detail' pk=agent.pk %}"
               class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
            <a href="{% url 'agents:agent-update' pk=agent.id %}"
               class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update Details</a>
          </div>
          <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Update</button>
          </form>
          <a href="{% url 'agents:agent-delete' pk=agent.pk %}"
             class="w-1/3 mt-3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
            Delete
          </a>
        </div>
        <img alt="ecommerce"
             class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
             src="https://dummyimage.com/400x400"
             height="300"
             width="300"/>
      </div>
    </div>
  </section>
{% endblock content %}