agents/urls.py
from django.urls import path

from .views import (
    AgentCreateView,
    AgentDeleteView,
    AgentDetailView,
    AgentListView,
    AgentUpdateView,
)

app_name = "agents"

urlpatterns = [
    path("", AgentListView.as_view(), name="agent-list"),
    path("create/", AgentCreateView.as_view(), name="agent-create"),
    path("agent/update/<int:pk>/", AgentUpdateView.as_view(), name="agent-update"),
    path("agent/delete/<int:pk>/", AgentDeleteView.as_view(), name="agent-delete"),
    path("agent/detail/<int:pk>/", AgentDetailView.as_view(), name="agent-detail"),
]

crm/urls.py
from django.urls import path

from . import views

app_name = "crm"

urlpatterns = [
    path("", views.LeadListView.as_view(), name="home"),
    path("create/", views.LeadCreateView.as_view(), name="lead-create"),
    path("update/<int:pk>/", views.LeadUpdateView.as_view(), name="lead-update"),
    path("delete/<int:pk>/", views.LeadDeleteView.as_view(), name="lead-delete"),
    path("detail/<int:pk>/", views.LeadDetailView.as_view(), name="lead-detail"),
    path(
        "assign-agent/<int:pk>/", views.AssignAgentView.as_view(), name="agent-assign"
    ),
    path("categories/", views.CategoryListView.as_view(), name="category-list"),
    path(
        "categories/<int:pk>/",
        views.CategoryDetailView.as_view(),
        name="category-detail",
    ),
    path(
        "categories/<int:pk>/update/",
        views.LeadCategoryUpdateView.as_view(),
        name="lead-category-update",
    ),
    path(
        "create/category/", views.CategoryCreateView.as_view(), name="category-create"
    ),
    path(
        "update/<int:pk>/category/",
        views.CategoryUpdateView.as_view(),
        name="category-update",
    ),
    path(
        "delete/<int:pk>/category",
        views.CategoryDeleteView.as_view(),
        name="category-delete",
    ),
]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import include, path

from crm.views import LandingPageView, SignupView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", LandingPageView.as_view(), name="landing-page"),
    path("leads/", include("crm.urls", namespace="crm")),
    path("agents/", include("agents.urls", namespace="agents")),
    path("signup/", SignupView.as_view(), name="signup"),
    path("login/", LoginView.as_view(redirect_authenticated_user=True), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("reset_password/", PasswordResetView.as_view(), name="reset_password"),
    path(
        "password_reset_done/",
        PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "password_reset_complete/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    is_organizer = models.BooleanField(
        verbose_name="Organizer",
        default=True,
        help_text="Designates whether the user is a Organizer",
    )
    is_agent = models.BooleanField(
        verbose_name="Agent",
        default=False,
        help_text="Designates whether the user is a Agent",
    )


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Lead(models.Model):
    first_name = models.CharField(_("First Name"), max_length=20)
    last_name = models.CharField(_("Last Name"), max_length=20)
    age = models.IntegerField(_("Age"), default=0)
    description = models.TextField(_("Description"))
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField(_("Email Address"), max_length=254)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey(
        "Agent",
        on_delete=models.SET_NULL,
        verbose_name=_("Agent Assigned"),
        null=True,
        blank=True,
    )
    category = models.ForeignKey(
        "Category",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="leads",
    )

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"


class Agent(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, verbose_name=_("User Agent")
    )
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.user.first_name} {self.user.last_name}"


class Category(models.Model):
    name = models.CharField(max_length=30)  # New, Contacted, Converted, Unconverted
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

crm/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, UsernameField

from .models import Agent, Category, Lead

User = get_user_model()


class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = [
            "first_name",
            "last_name",
            "age",
            "email",
            "phone_number",
            "description",
            "agent",
        ]


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            "username",
        ]
        # field_classes = {"username": UsernameField}


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {"username": UsernameField}


class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        agents = Agent.objects.filter(organization=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields["agent"].queryset = agents


class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ("category",)


class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ("name",)


# class LeadForm(forms.Form):
#     first_name = forms.CharField()
#     last_name = forms.CharField()
#     age = forms.IntegerField(min_value=0)

crm/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    FormView,
    ListView,
    TemplateView,
    UpdateView,
)

from agents.mixins import OrganizerAndLoginRequiredMixin

from .forms import (
    AssignAgentForm,
    CategoryModelForm,
    CustomUserCreationForm,
    LeadCategoryUpdateForm,
    LeadModelForm,
)
from .models import Category, Lead

# Create your views here.


class SignupView(CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    # for authenticated users to return to the crm home page instead of going into the signup page
    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect("crm:home")
        return super(SignupView, self).get(request, *args, **kwargs)

    def get_success_url(self) -> str:
        return reverse("login")


class LandingPageView(TemplateView):
    template_name = "crm/landing.html"


class LeadListView(LoginRequiredMixin, ListView):
    template_name = "crm/lead_list.html"
    context_object_name = "leads"

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            queryset = Lead.objects.filter(
                organization=user.userprofile, agent__isnull=False
            )
        else:
            queryset = Lead.objects.filter(
                organization=user.agent.organization, agent__isnull=False
            )
            # filter for the agent logged in
            queryset = queryset.filter(agent__user=user)
        return queryset

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(LeadListView, self).get_context_data(**kwargs)
        if user.is_organizer:
            queryset = Lead.objects.filter(
                organization=user.userprofile, agent__isnull=True
            )
            context.update(
                {
                    "unassigned_leads": queryset,
                }
            )
        return context


class LeadDetailView(LoginRequiredMixin, DetailView):
    template_name = "crm/lead_detail.html"
    context_object_name = "lead"

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)
            # filter for the agent logged in
            queryset = queryset.filter(agent__user=user)
        return queryset


class LeadCreateView(OrganizerAndLoginRequiredMixin, CreateView):
    """Create a CBV with model form so that it is saved into the database directly when submitted through the webpage and deal with sending emails to either client leads or to created agents.

    Args:
        CreateView (generic views): django builtin view for creating database rows which is inherited by the current view.

    Returns:
        HTTPResponse: An HTTPResponse which renders a template on the browser.
    """

    template_name = "crm/lead_create.html"
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("crm:home")

    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organization = self.request.user.userprofile
        lead.save()
        # TODO: send email
        send_mail(
            subject="A Lead has been created.",
            message="Go to the site to see the new lead.",
            from_email="test@test.com",
            recipient_list=["test2@test.com"],
        )
        messages.success(self.request, "You have successfully create a lead.")
        return super(LeadCreateView, self).form_valid(form)


class LeadUpdateView(OrganizerAndLoginRequiredMixin, UpdateView):
    template_name = "crm/lead_update.html"
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse("crm:home")

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        queryset = Lead.objects.filter(organization=user.userprofile)
        return queryset


class LeadDeleteView(OrganizerAndLoginRequiredMixin, DeleteView):
    template_name = "crm/lead_delete.html"

    def get_success_url(self) -> str:
        return reverse("crm:home")

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        queryset = Lead.objects.filter(organization=user.userprofile)
        return queryset


class AssignAgentView(OrganizerAndLoginRequiredMixin, FormView):
    template_name = "crm/assign_agent.html"
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update({"request": self.request})
        return kwargs

    def get_success_url(self):
        return reverse("crm:home")

    def form_valid(self, form):
        agent = form.cleaned_data["agent"]
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)


class CategoryListView(LoginRequiredMixin, ListView):
    template_name = "crm/category_list.html"
    context_object_name = "category_list"

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            queryset = Category.objects.filter(organization=user.userprofile)
        else:
            queryset = Category.objects.filter(organization=user.agent.organization)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)
        context.update(
            {"unassigned_lead_count": queryset.filter(category__isnull=True).count()}
        )
        return context


class CategoryDetailView(LoginRequiredMixin, DetailView):
    template_name = "crm/category_detail.html"
    context_object_name = "category"

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            queryset = Category.objects.filter(organization=user.userprofile)
        else:
            queryset = Category.objects.filter(organization=user.agent.organization)

        return queryset

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     # category = self.get_object()
    #     # qs = Lead.objects.filter(category=category)
    #     leads = self.get_object().leads.all()
    #     context.update({"leads": leads})
    #     return context


class LeadCategoryUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "crm/lead_category_update.html"
    form_class = LeadCategoryUpdateForm

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)
            queryset = queryset.filter(agent__user=user)
        return queryset

    def get_success_url(self):
        return reverse("crm:lead-detail", kwargs={"pk": self.get_object().pk})


class CategoryCreateView(OrganizerAndLoginRequiredMixin, CreateView):

    template_name = "crm/category_create.html"
    form_class = CategoryModelForm

    def get_success_url(self):
        return reverse("crm:category-list")

    def form_valid(self, form):
        category = form.save(commit=False)
        category.organization = self.request.user.userprofile
        category.save()
        return super(CategoryCreateView, self).form_valid(form)


class CategoryUpdateView(OrganizerAndLoginRequiredMixin, UpdateView):

    template_name = "crm/category_update.html"
    form_class = CategoryModelForm

    def get_success_url(self):
        return reverse("crm:category-list")

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            queryset = Category.objects.filter(organization=user.userprofile)
        else:
            queryset = Category.objects.filter(organization=user.agent.organization)

        return queryset


class CategoryDeleteView(OrganizerAndLoginRequiredMixin, DeleteView):
    template_name = "crm/category_delete.html"

    def get_success_url(self):
        return reverse("crm:category-list")

    def get_queryset(self):
        user = self.request.user
        # initial queryset of leads for the entire organization
        if user.is_organizer:
            queryset = Category.objects.filter(organization=user.userprofile)
        else:
            queryset = Category.objects.filter(organization=user.agent.organization)

        return queryset

templates/crm/assign_agent.html
{% extends "crm/base.html" %}
{% block content %}
  <a href="{% url 'crm:home' %}">Go back to leads</a>
  <hr/>
  <h1>Assign an agent to this lead</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock content %}

templates/crm/category_detail.html
{% extends "crm/base.html" %}
{% block content %}
  <section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{ category.name }}</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">These are the leads under this category</p>
        <a href="{% url 'crm:category-update' pk=category.pk %}"
           class="hover:text-blue-600">Update</a>
        <a href="{% url 'crm:category-delete' pk=category.pk %}"
           class="hover:text-red-600">Delete</a>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
                First Name
              </th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Last Name</th>
            </tr>
          </thead>
          <tbody>
            {% for lead in category.leads.all %}
              <tr>
                <td class="px-4 py-3">
                  <a class="hover:text-blue-500"
                     href="{% url 'crm:lead-detail' pk=lead.pk %}">{{ lead.first_name }}</a>
                </td>
                <td class="px-4 py-3">{{ lead.last_name }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>
{% endblock content %}

templates/crm/category_list.html
{% extends "crm/base.html" %}
{% block content %}
  <section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">These categories segment the leads</p>
        <a href="{% url 'crm:category-create' %}" class="hover:text-blue-600">Create Category</a>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
                Name
              </th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Lead Count</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="px-4 py-3">Unassigned</td>
              <td class="px-4 py-3">{{ unassigned_lead_count }}</td>
            </tr>
            {% for category in category_list %}
              <tr>
                <td class="px-4 py-3">
                  <a href="{% url 'crm:category-detail' pk=category.pk %}">{{ category.name }}</a>
                </td>
                <td class="px-4 py-3">{{ category.leads.count }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>
{% endblock content %}

templates/crm/lead_detail.html
{% extends "crm/base.html" %}
{% block title %}
  CRM - Detail
{% endblock title %}
{% block content %}
  <section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
          <div class="flex mb-4">
            <a href="{% url 'crm:lead-detail' lead.pk %}"
               class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
              Overview
            </a>
            <a href="{% url 'crm:lead-category-update' lead.pk %}"
               class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Category
            </a>
            <a href="{% url 'crm:lead-update' lead.pk %}"
               class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Update Details
            </a>
          </div>
          <p class="leading-relaxed mb-4">{{ lead.description }}</p>
          <div class="flex border-t border-gray-300 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900">{{ lead.age }}</span>
          </div>
          <div class="flex border-t border-gray-300 py-2">
            <span class="text-gray-500">Email</span>
            <span class="ml-auto text-gray-900">{{ lead.email }}</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-300 py-2">
            <span class="text-gray-500">Phone Number</span>
            <span class="ml-auto text-gray-900">{{ lead.phone_number }}</span>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

templates/crm/lead_list.html
{% extends "crm/base.html" %}
{% block title %}
  CRM - HOME
{% endblock title %}
{% block content %}
  <section class="text-gray-700 body-font">
    <div class="container px-5 py-10 mx-auto flex flex-wrap">
      <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
        <div>
          <h1 class="text-4xl text-gray-800">Leads</h1>
          <a class="text-gray-500 hover:text-blue-500"
             href="{% url 'crm:category-list' %}">View categories</a>
        </div>
        {% if request.user.is_organizer %}
          <div>
            <a class="text-gray-500 hover:text-blue-500"
               href="{% url 'crm:lead-create' %}">Create a new lead</a>
          </div>
        {% endif %}
      </div>
      <div class="flex flex-col w-full">
        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
          <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
              <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                  <tr>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">First Name</th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Last Name</th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Age</th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Email</th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      Cell Phone Number
                    </th>
                    <th scope="col"
                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Category</th>
                    <th scope="col" class="relative px-6 py-3">
                      <span class="sr-only">Edit</span>
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {% for lead in leads %}
                    <tr class="bg-white">
                      <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{ lead.first_name }}</td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ lead.last_name }}</td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ lead.age }}</td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ lead.email }}</td>
                      <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">{{ lead.phone_number }}</td>
                      <td class="px-6 py-4 whitespace-nowrap">
                        {% if lead.category %}
                          <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                            {{ lead.category.name }}
                          </span>
                        {% else %}
                          <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">Unassigned</span>
                        {% endif %}
                      </td>
                      <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <a href="{% url 'crm:lead-update' lead.pk %}"
                           class="text-indigo-600 hover:text-indigo-900">Edit</a>
                      </td>
                    </tr>
                  {% empty %}
                    <p>There are currently no leads</p>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      {% if unassigned_leads.exists %}
        <div class="mt-5 flex flex-wrap -m-4">
          <div class="p-4 w-full">
            <h1 class="text-4xl text-gray-800">Unassigned leads</h1>
          </div>
          {% for lead in unassigned_leads %}
            <div class="p-4 lg:w-1/2 md:w-full">
              <div class="flex border-2 rounded-lg border-gray-200 p-8 sm:flex-row flex-col">
                <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                  <svg fill="none"
                       stroke="currentColor"
                       stroke-linecap="round"
                       stroke-linejoin="round"
                       stroke-width="2"
                       class="w-8 h-8"
                       viewBox="0 0 24 24">
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
                  </svg>
                </div>
                <div class="flex-grow">
                  <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{ lead.first_name }} {{ lead.last_name }}</h2>
                  <p class="leading-relaxed text-base">{{ lead.description }}</p>
                  <a href="{% url 'crm:agent-assign' lead.pk %}"
                     class="mt-3 text-indigo-500 inline-flex items-center">
                    Assign an agent
                    <svg fill="none"
                         stroke="currentColor"
                         stroke-linecap="round"
                         stroke-linejoin="round"
                         stroke-width="2"
                         class="w-4 h-4 ml-2"
                         viewBox="0 0 24 24">
                      <path d="M5 12h14M12 5l7 7-7 7" />
                    </svg>
                  </a>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      {% endif %}
    </div>
  </section>
{% endblock content %}

templates/crm/lead_update.html
{% extends "crm/base.html" %}
{% load tailwind_filters %}
{% block title %}
  CRM - Change
{% endblock title %}
{% block content %}
  <section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
          <div class="flex mb-4">
            <a href="{% url 'crm:lead-detail' lead.pk %}"
               class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Overview
            </a>
            <a href="{% url 'crm:lead-category-update' lead.pk %}"
               class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
              Category
            </a>
            <a href="{% url 'crm:lead-update' lead.pk %}"
               class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
              Update Details
            </a>
          </div>
          <form form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit"
                    class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
          </form>
          <div class="mt-5 py-5 border-t border-gray-200">
            <a href="{% url 'crm:lead-delete' lead.pk %}"
               class="w-1/2 mt-3 text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded">
              Delete
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}